### ISSUE TITLE
[comments] Merge command hangs when source file contents out-of-indent comments

### ISSUE THREAD

**Issue by yannoff** [yannoff/yamltools#26]
## Problem

Given the following source & destination files:

**source.yaml**
```yaml
name: yannoff/yamltools
description: 'A command-line Swiss-Knife for YAML files'
homepage: 'https://github.com/yannoff/yamltools'
type: console-script
require:
    php: '>=5.6.40'
# Should work even without, since the JSON ext is now a built-in php module
    ext-json: '*'
    symfony/yaml: ^3.4
```

**dest.yaml**
```yaml
name: yannoff/yamltools
description: 'A command-line Swiss-Knife for YAML files'
homepage: 'https://github.com/yannoff/yamltools'
type: console-script
require:
    php: '>=5.6.40'
    ext-json: '*'
    symfony/yaml: ^3.4
```

The following merge command attempt hangs and never terminate:

```bash
$ yamltools yaml:comments:merge source.yaml dest.yaml
```

## Explanation

The `YPath` calculated by the [`Contents::getParentYPath()`](https://github.com/yannoff/y-a-m-l/blob/864be87d351797e270b63cbb755bc9f456afe407/src/Contents.php#L289) method of the [`yannoff/y-a-m-l`](https://github.com/yannoff/y-a-m-l) library is wrong, since the comment is mistakenly interpreted as the parent level line, whereas it should not
